version: '3'
services:
  app:
    container_name: node-docker-container
    environment:
      MONGO_URI: mongodb://mongo:27017
    restart: always
    build: .
    ports:
      - '8081:8081'
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    