POST http://localhost:5000/memes?name=manoj%20kumar&url=https://images.pexels.com/photos/3573382/pexels-photo-3573382.jpeg&caption=This%20is%20a%20mem


###
GET http://localhost:5000/memes


### 
GET http://localhost:5000/memes/601d7dcf7af052877a2fa70b


###
PATCH http://localhost:5000/memes/60213d541d41326691ffaa2f HTTP/1.1
Content-Type: application/json

{
    "caption": "This is a"
}
###

POST http://localhost:5000/like/60213d541d41326691ffaa2f HTTP/1.1
